name: Build and Release

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  build-and-release:
    if: github.event.pull_request.merged == true
    runs-on: windows-latest

    env:
      KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Decode keystore
        run: |
          echo "${env:KEYSTORE_BASE64}" | base64 -d > keystore.jks

      - name: Extract version from Gradle file
        id: version
        shell: pwsh
        run: |
          $versionLine = Get-Content build.gradle.kts | Where-Object { $_ -match 'val version: String' }
          $version = ($versionLine -split '"')[1]
          echo "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "version=$version" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

      - name: Build APK signed
        run: |
          ./gradlew assembleRelease `
            -Pandroid.injected.signing.store.file=keystore.jks `
            -Pandroid.injected.signing.store.password=${env:KEYSTORE_PASSWORD} `
            -Pandroid.injected.signing.key.alias=${env:KEY_ALIAS} `
            -Pandroid.injected.signing.key.password=${env:KEY_PASSWORD}

      - name: Build MSI
        run: ./gradlew packageMsi

      - name: Rename generated artifacts
        run: |
          mv composeApp/build/outputs/apk/release/composeApp-release.apk gh-almacen-v${{ env.VERSION }}.apk
          mv composeApp/build/compose/binaries/main/msi/com.cocot3ro.gh.almacen-${{ env.VERSION }}.msi gh-almacen-v${{ env.VERSION }}.msi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: ${{ steps.version.outputs.version }}
          body: ${{ github.event.pull_request.body }}
          files: |
            gh-almacen-v${{ steps.version.outputs.version }}.apk
            gh-almacen-v${{ steps.version.outputs.version }}.msi

      - name: Generate versions.json
        shell: bash
        run: |
          echo "{
            \"desktop\": {
              \"version\": \"${{ steps.version.outputs.version }}\",
              \"url\": \"https://github.com/${{ github.repository }}/releases/download/v${{ steps.version.outputs.version }}/gh-almacen-v${{ steps.version.outputs.version }}.msi\"
            },
            \"android\": {
              \"version\": \"${{ steps.version.outputs.version }}\",
              \"url\": \"https://github.com/${{ github.repository }}/releases/download/v${{ steps.version.outputs.version }}/gh-almacen-v${{ steps.version.outputs.version }}.apk\"
            }
          }" > versions.json

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
          path: gh-pages

      - name: Copy versions.json to gh-pages
        run: |
          Copy-Item versions.json gh-pages\versions.json -Force

      - name: Commit and push versions.json
        working-directory: gh-pages
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add versions.json
          git commit -m "chore: update versions.json to v${{ steps.version.outputs.version }}" || echo "No changes to commit"
          git push origin gh-pages
